"""financial planning layer

Revision ID: 81b84ddfbdc3
Revises: f4153ba4b21b
Create Date: 2026-07-03 14:20:54.559675
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "81b84ddfbdc3"
down_revision: str | None = "f4153ba4b21b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budget_alerts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("budget_id", sa.Uuid(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acknowledged", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_budget_alerts_budget_id"), "budget_alerts", ["budget_id"], unique=False
    )
    op.create_index(
        op.f("ix_budget_alerts_created_at"), "budget_alerts", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_budget_alerts_user_id"), "budget_alerts", ["user_id"], unique=False)
    op.create_table(
        "budget_allocations",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("budget_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("server_seq", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_budget_allocations_budget_id"), "budget_allocations", ["budget_id"], unique=False
    )
    op.create_index(
        op.f("ix_budget_allocations_server_seq"), "budget_allocations", ["server_seq"], unique=False
    )
    op.create_index(
        op.f("ix_budget_allocations_user_id"), "budget_allocations", ["user_id"], unique=False
    )
    op.create_table(
        "budgets",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column(
            "period_type",
            sa.Enum("WEEKLY", "MONTHLY", "CUSTOM", name="budgetperiodtype", native_enum=False),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("overall_amount_minor", sa.BigInteger(), nullable=True),
        sa.Column("custom_period_days", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("server_seq", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_budgets_server_seq"), "budgets", ["server_seq"], unique=False)
    op.create_index(op.f("ix_budgets_user_id"), "budgets", ["user_id"], unique=False)
    op.create_table(
        "goal_contributions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("goal_id", sa.Uuid(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("transaction_id", sa.Uuid(), nullable=True),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("server_seq", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_goal_contributions_goal_id"), "goal_contributions", ["goal_id"], unique=False
    )
    op.create_index(
        op.f("ix_goal_contributions_occurred_at"),
        "goal_contributions",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_goal_contributions_server_seq"), "goal_contributions", ["server_seq"], unique=False
    )
    op.create_index(
        op.f("ix_goal_contributions_user_id"), "goal_contributions", ["user_id"], unique=False
    )
    op.create_table(
        "goal_milestones",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("goal_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("target_amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("reached_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("server_seq", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_goal_milestones_goal_id"), "goal_milestones", ["goal_id"], unique=False
    )
    op.create_index(
        op.f("ix_goal_milestones_server_seq"), "goal_milestones", ["server_seq"], unique=False
    )
    op.create_index(
        op.f("ix_goal_milestones_user_id"), "goal_milestones", ["user_id"], unique=False
    )
    op.create_table(
        "goals",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column(
            "goal_type",
            sa.Enum(
                "SAVINGS",
                "PURCHASE",
                "EMERGENCY_FUND",
                "EDUCATION",
                "TRAVEL",
                "CUSTOM",
                name="goaltype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("target_amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE", "PAUSED", "ACHIEVED", "ARCHIVED", name="goalstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("server_seq", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_goals_server_seq"), "goals", ["server_seq"], unique=False)
    op.create_index(op.f("ix_goals_status"), "goals", ["status"], unique=False)
    op.create_index(op.f("ix_goals_user_id"), "goals", ["user_id"], unique=False)
    op.create_table(
        "recurring_series",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "RENT",
                "EMI",
                "SIP",
                "UTILITY",
                "SUBSCRIPTION",
                "SALARY",
                "OTHER",
                name="recurringkind",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "direction",
            sa.Enum("INFLOW", "OUTFLOW", name="recurringdirection", native_enum=False),
            nullable=False,
        ),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "interval",
            sa.Enum(
                "DAILY",
                "WEEKLY",
                "MONTHLY",
                "QUARTERLY",
                "YEARLY",
                name="recurrenceinterval",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("anchor_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("next_due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("account_id", sa.Uuid(), nullable=True),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("merchant_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING_APPROVAL",
                "ACTIVE",
                "PAUSED",
                "CANCELLED",
                name="recurringstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("detected", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=True),
        sa.Column("is_subscription", sa.Boolean(), nullable=False),
        sa.Column("vendor", sa.String(length=160), nullable=True),
        sa.Column(
            "billing_cycle",
            sa.Enum(
                "WEEKLY", "MONTHLY", "QUARTERLY", "YEARLY", name="billingcycle", native_enum=False
            ),
            nullable=True,
        ),
        sa.Column("auto_renew", sa.Boolean(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("server_seq", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recurring_series_is_subscription"),
        "recurring_series",
        ["is_subscription"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recurring_series_merchant_id"), "recurring_series", ["merchant_id"], unique=False
    )
    op.create_index(
        op.f("ix_recurring_series_next_due_at"), "recurring_series", ["next_due_at"], unique=False
    )
    op.create_index(
        op.f("ix_recurring_series_server_seq"), "recurring_series", ["server_seq"], unique=False
    )
    op.create_index(
        op.f("ix_recurring_series_status"), "recurring_series", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_recurring_series_user_id"), "recurring_series", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recurring_series_user_id"), table_name="recurring_series")
    op.drop_index(op.f("ix_recurring_series_status"), table_name="recurring_series")
    op.drop_index(op.f("ix_recurring_series_server_seq"), table_name="recurring_series")
    op.drop_index(op.f("ix_recurring_series_next_due_at"), table_name="recurring_series")
    op.drop_index(op.f("ix_recurring_series_merchant_id"), table_name="recurring_series")
    op.drop_index(op.f("ix_recurring_series_is_subscription"), table_name="recurring_series")
    op.drop_table("recurring_series")
    op.drop_index(op.f("ix_goals_user_id"), table_name="goals")
    op.drop_index(op.f("ix_goals_status"), table_name="goals")
    op.drop_index(op.f("ix_goals_server_seq"), table_name="goals")
    op.drop_table("goals")
    op.drop_index(op.f("ix_goal_milestones_user_id"), table_name="goal_milestones")
    op.drop_index(op.f("ix_goal_milestones_server_seq"), table_name="goal_milestones")
    op.drop_index(op.f("ix_goal_milestones_goal_id"), table_name="goal_milestones")
    op.drop_table("goal_milestones")
    op.drop_index(op.f("ix_goal_contributions_user_id"), table_name="goal_contributions")
    op.drop_index(op.f("ix_goal_contributions_server_seq"), table_name="goal_contributions")
    op.drop_index(op.f("ix_goal_contributions_occurred_at"), table_name="goal_contributions")
    op.drop_index(op.f("ix_goal_contributions_goal_id"), table_name="goal_contributions")
    op.drop_table("goal_contributions")
    op.drop_index(op.f("ix_budgets_user_id"), table_name="budgets")
    op.drop_index(op.f("ix_budgets_server_seq"), table_name="budgets")
    op.drop_table("budgets")
    op.drop_index(op.f("ix_budget_allocations_user_id"), table_name="budget_allocations")
    op.drop_index(op.f("ix_budget_allocations_server_seq"), table_name="budget_allocations")
    op.drop_index(op.f("ix_budget_allocations_budget_id"), table_name="budget_allocations")
    op.drop_table("budget_allocations")
    op.drop_index(op.f("ix_budget_alerts_user_id"), table_name="budget_alerts")
    op.drop_index(op.f("ix_budget_alerts_created_at"), table_name="budget_alerts")
    op.drop_index(op.f("ix_budget_alerts_budget_id"), table_name="budget_alerts")
    op.drop_table("budget_alerts")
    # ### end Alembic commands ###
