"""product experience layer

Revision ID: 8eab1c0437c0
Revises: 81b84ddfbdc3
Create Date: 2026-07-03 19:58:33.313298
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8eab1c0437c0"
down_revision: str | None = "81b84ddfbdc3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "GOAL_REMINDER",
                "BUDGET_WARNING",
                "SUBSCRIPTION_RENEWAL",
                "UPCOMING_BILL",
                "FORECAST_WARNING",
                "GOAL_COMPLETION",
                name="notificationtype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "channel",
            sa.Enum("IN_APP", "PUSH", "EMAIL", name="notificationchannel", native_enum=False),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.String(length=1000), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED", "SENT", "READ", "DISMISSED", name="notificationstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "dedupe_key", name="uq_notif_event"),
    )
    op.create_index(
        op.f("ix_notification_events_created_at"),
        "notification_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_events_status"), "notification_events", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_notification_events_user_id"), "notification_events", ["user_id"], unique=False
    )
    op.create_table(
        "notification_preferences",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("in_app_enabled", sa.Boolean(), nullable=False),
        sa.Column("push_enabled", sa.Boolean(), nullable=False),
        sa.Column("email_enabled", sa.Boolean(), nullable=False),
        sa.Column("quiet_hours_start", sa.Integer(), nullable=True),
        sa.Column("quiet_hours_end", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_preferences_user_id"),
        "notification_preferences",
        ["user_id"],
        unique=True,
    )
    op.create_table(
        "notification_rules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "GOAL_REMINDER",
                "BUDGET_WARNING",
                "SUBSCRIPTION_RENEWAL",
                "UPCOMING_BILL",
                "FORECAST_WARNING",
                "GOAL_COMPLETION",
                name="notificationtype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("lead_time_days", sa.Integer(), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "type", name="uq_notif_rule"),
    )
    op.create_index(
        op.f("ix_notification_rules_user_id"), "notification_rules", ["user_id"], unique=False
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "period",
            sa.Enum("WEEKLY", "MONTHLY", "QUARTERLY", name="reviewperiod", native_enum=False),
            nullable=False,
        ),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("total_spent_minor", sa.BigInteger(), nullable=False),
        sa.Column("total_income_minor", sa.BigInteger(), nullable=False),
        sa.Column("net_cashflow_minor", sa.BigInteger(), nullable=False),
        sa.Column("savings_rate_bps", sa.Integer(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "period", "period_start", name="uq_review_period"),
    )
    op.create_index(op.f("ix_reviews_period"), "reviews", ["period"], unique=False)
    op.create_index(op.f("ix_reviews_period_start"), "reviews", ["period_start"], unique=False)
    op.create_index(op.f("ix_reviews_user_id"), "reviews", ["user_id"], unique=False)
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("week_start_day", sa.Integer(), nullable=False),
        sa.Column("monthly_income_minor", sa.BigInteger(), nullable=True),
        sa.Column(
            "financial_priority",
            sa.Enum(
                "SAVINGS_FIRST",
                "GOAL_FIRST",
                "DEBT_REDUCTION_FIRST",
                "BALANCED",
                name="financialpriority",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "risk_profile",
            sa.Enum(
                "CONSERVATIVE", "MODERATE", "AGGRESSIVE", name="riskprofile", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("server_seq", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_profiles_server_seq"), "user_profiles", ["server_seq"], unique=False
    )
    op.create_index(op.f("ix_user_profiles_user_id"), "user_profiles", ["user_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_profiles_user_id"), table_name="user_profiles")
    op.drop_index(op.f("ix_user_profiles_server_seq"), table_name="user_profiles")
    op.drop_table("user_profiles")
    op.drop_index(op.f("ix_reviews_user_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_period_start"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_period"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_notification_rules_user_id"), table_name="notification_rules")
    op.drop_table("notification_rules")
    op.drop_index(
        op.f("ix_notification_preferences_user_id"), table_name="notification_preferences"
    )
    op.drop_table("notification_preferences")
    op.drop_index(op.f("ix_notification_events_user_id"), table_name="notification_events")
    op.drop_index(op.f("ix_notification_events_status"), table_name="notification_events")
    op.drop_index(op.f("ix_notification_events_created_at"), table_name="notification_events")
    op.drop_table("notification_events")
    # ### end Alembic commands ###
