"""initial platform schema

Revision ID: f4153ba4b21b
Revises:
Create Date: 2026-07-03 08:14:54.940473
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f4153ba4b21b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "CASH",
                "SAVINGS",
                "CURRENT",
                "CREDIT_CARD",
                "WALLET",
                "INVESTMENT",
                name="accounttype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("opening_balance_minor", sa.BigInteger(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("institution", sa.String(length=120), nullable=True),
        sa.Column("external_ref", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("server_seq", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_accounts_server_seq"), "accounts", ["server_seq"], unique=False)
    op.create_index(op.f("ix_accounts_user_id"), "accounts", ["user_id"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("actor_type", sa.String(length=20), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=True),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("diff", sa.JSON(), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_log_created_at"), "audit_log", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_log_user_id"), "audit_log", ["user_id"], unique=False)
    op.create_table(
        "categories",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("icon", sa.String(length=60), nullable=True),
        sa.Column("color", sa.String(length=9), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("server_seq", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_categories_parent_id"), "categories", ["parent_id"], unique=False)
    op.create_index(op.f("ix_categories_server_seq"), "categories", ["server_seq"], unique=False)
    op.create_index(op.f("ix_categories_user_id"), "categories", ["user_id"], unique=False)
    op.create_table(
        "categorization_rules",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "logic", sa.Enum("ALL", "ANY", name="rulelogic", native_enum=False), nullable=False
        ),
        sa.Column("conditions", sa.JSON(), nullable=False),
        sa.Column("set_category_id", sa.Uuid(), nullable=True),
        sa.Column("set_merchant_id", sa.Uuid(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("stop_processing", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("server_seq", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_categorization_rules_priority"), "categorization_rules", ["priority"], unique=False
    )
    op.create_index(
        op.f("ix_categorization_rules_server_seq"),
        "categorization_rules",
        ["server_seq"],
        unique=False,
    )
    op.create_index(
        op.f("ix_categorization_rules_user_id"), "categorization_rules", ["user_id"], unique=False
    )
    op.create_table(
        "ledger_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("txn_version", sa.Integer(), nullable=False),
        sa.Column("is_reversal", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ledger_entries_account_id"), "ledger_entries", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_ledger_entries_transaction_id"), "ledger_entries", ["transaction_id"], unique=False
    )
    op.create_index(op.f("ix_ledger_entries_user_id"), "ledger_entries", ["user_id"], unique=False)
    op.create_table(
        "merchants",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("normalized_name", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("server_seq", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_merchants_normalized_name"), "merchants", ["normalized_name"], unique=False
    )
    op.create_index(op.f("ix_merchants_server_seq"), "merchants", ["server_seq"], unique=False)
    op.create_index(op.f("ix_merchants_user_id"), "merchants", ["user_id"], unique=False)
    op.create_table(
        "outbox",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("event_name", sa.String(length=100), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_outbox_created_at"), "outbox", ["created_at"], unique=False)
    op.create_index(op.f("ix_outbox_user_id"), "outbox", ["user_id"], unique=False)
    op.create_table(
        "sync_sequence",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("next_seq", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "transactions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("counter_account_id", sa.Uuid(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "EXPENSE",
                "INCOME",
                "TRANSFER",
                "REFUND",
                "ADJUSTMENT",
                name="transactiontype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "CLEARED", "RECONCILED", name="transactionstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("merchant_id", sa.Uuid(), nullable=True),
        sa.Column("counterparty", sa.String(length=200), nullable=True),
        sa.Column("note", sa.String(length=1000), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "MANUAL", "RULE", "IMPORT", "RECURRING", name="transactionsource", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "categorization_source",
            sa.Enum(
                "MANUAL",
                "USER_RULE",
                "ML_MODEL",
                "DEFAULT",
                name="categorizationsource",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("external_ref", sa.String(length=200), nullable=True),
        sa.Column("related_transaction_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("server_seq", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transactions_server_seq"), "transactions", ["server_seq"], unique=False
    )
    op.create_index(
        "ix_txn_user_account_occurred",
        "transactions",
        ["user_id", "account_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_txn_user_category_occurred",
        "transactions",
        ["user_id", "category_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_txn_user_merchant_occurred",
        "transactions",
        ["user_id", "merchant_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_txn_user_occurred", "transactions", ["user_id", "occurred_at"], unique=False
    )
    op.create_index("ix_txn_user_seq", "transactions", ["user_id", "server_seq"], unique=False)
    op.create_index(
        "ix_txn_user_source_extref",
        "transactions",
        ["user_id", "source", "external_ref"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_txn_user_source_extref", table_name="transactions")
    op.drop_index("ix_txn_user_seq", table_name="transactions")
    op.drop_index("ix_txn_user_occurred", table_name="transactions")
    op.drop_index("ix_txn_user_merchant_occurred", table_name="transactions")
    op.drop_index("ix_txn_user_category_occurred", table_name="transactions")
    op.drop_index("ix_txn_user_account_occurred", table_name="transactions")
    op.drop_index(op.f("ix_transactions_server_seq"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_table("sync_sequence")
    op.drop_index(op.f("ix_outbox_user_id"), table_name="outbox")
    op.drop_index(op.f("ix_outbox_created_at"), table_name="outbox")
    op.drop_table("outbox")
    op.drop_index(op.f("ix_merchants_user_id"), table_name="merchants")
    op.drop_index(op.f("ix_merchants_server_seq"), table_name="merchants")
    op.drop_index(op.f("ix_merchants_normalized_name"), table_name="merchants")
    op.drop_table("merchants")
    op.drop_index(op.f("ix_ledger_entries_user_id"), table_name="ledger_entries")
    op.drop_index(op.f("ix_ledger_entries_transaction_id"), table_name="ledger_entries")
    op.drop_index(op.f("ix_ledger_entries_account_id"), table_name="ledger_entries")
    op.drop_table("ledger_entries")
    op.drop_index(op.f("ix_categorization_rules_user_id"), table_name="categorization_rules")
    op.drop_index(op.f("ix_categorization_rules_server_seq"), table_name="categorization_rules")
    op.drop_index(op.f("ix_categorization_rules_priority"), table_name="categorization_rules")
    op.drop_table("categorization_rules")
    op.drop_index(op.f("ix_categories_user_id"), table_name="categories")
    op.drop_index(op.f("ix_categories_server_seq"), table_name="categories")
    op.drop_index(op.f("ix_categories_parent_id"), table_name="categories")
    op.drop_table("categories")
    op.drop_index(op.f("ix_audit_log_user_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_created_at"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_accounts_user_id"), table_name="accounts")
    op.drop_index(op.f("ix_accounts_server_seq"), table_name="accounts")
    op.drop_table("accounts")
    # ### end Alembic commands ###
